[cherry-pick 1.5.2] pin pydantic to <2.0 (#1645) (#1107)
* Restrict `pydantic<2.0.0` due to breaking changes (#1104)

> Pydantic V2 is a ground-up rewrite that offers many new features, performance improvements, and some breaking changes compared to Pydantic V1.

```
deepsparse/pipeline.py:822: in <module>
    class PipelineConfig(BaseModel):
...
NameError: Field "model_path" has conflict with protected namespace "model_"
```

* bump version to 1.5.2

---------

Co-authored-by: Michael Goin <michael@neuralmagic.com>